### ISSUE TITLE
Убрать все assert'ы и  использовать вместо них @NotNull и @Nullable

### ISSUE THREAD

**Issue by KSolovyev** [SoBeard/tapsquare_server#1]
assert'ы ухудшают читаемость кода. Кроме того, когда используете аннотации, надобности в них нет, идея сама добавит нужные проверки на этапе загрузки классов. Как добавить инспекции в проект и как их использовать можно почитать в нашем блоге https://park.mail.ru/blog/topic/3850/

**Comment by MysterySuperhero** [comment]
Сделано.
